# --- !Ups
CREATE TABLE ACTIVITY_RECIPIENT_READ (
  "USERCODE" nvarchar2 (10) NOT NULL,
  "NOTIFICATIONS_LAST_READ" TIMESTAMP (6) NOT NULL,
  "ACTIVITIES_LAST_READ" TIMESTAMP (6),
  CONSTRAINT "ACTIVITY_RECIPIENT_READ_PK" PRIMARY KEY ("USERCODE")
);

# --- !Downs
DROP TABLE ACTIVITY_RECIPIENT_READ;