# --- !Ups
CREATE TABLE ACTIVITY (
  "ID" nvarchar2 (100) NOT NULL,
  "PROVIDER_ID" nvarchar2 (100) NOT NULL,
  "TYPE" nvarchar2 (100) NOT NULL,
  "TITLE" clob NOT NULL,
  "TEXT" clob NOT NULL,
  "REPLACED_BY_ID" nvarchar2 (100),
  "GENERATED_AT" TIMESTAMP (6) NOT NULL,
  "CREATED_AT" TIMESTAMP (6) NOT NULL,
  "SHOULD_NOTIFY" NUMBER (1, 0) DEFAULT 0 NOT NULL,
  CONSTRAINT "ACTIVITY_PK" PRIMARY KEY ("ID")
);

CREATE TABLE ACTIVITY_SCOPE (
  "ACTIVITY_ID" nvarchar2 (100) NOT NULL,
  "ID" nvarchar2 (100) NOT NULL,
  "NAME" nvarchar2 (255) NOT NULL,
  "VALUE" nvarchar2 (255) NOT NULL,
  "CREATED_AT" TIMESTAMP (6) NOT NULL,
  CONSTRAINT "ACTIVITY_SCOPE_PK" PRIMARY KEY ("ACTIVITY_ID", "ID"),
  CONSTRAINT "ACTIVITY_SCOPE_FK" FOREIGN KEY ("ACTIVITY_ID") REFERENCES ACTIVITY("ID")
);

CREATE TABLE ACTIVITY_RECIPIENT (
  "ACTIVITY_ID" nvarchar2 (100) NOT NULL,
  "USERCODE" nvarchar2 (10) NOT NULL,
  "CREATED_AT" TIMESTAMP (6) NOT NULL,
  "SENT_AT" TIMESTAMP (6),
  "SEEN_AT" TIMESTAMP (6),
  "DISMISSED_AT" TIMESTAMP (6),
  CONSTRAINT "ACTIVITY_DELIVERIES_PK" PRIMARY KEY ("ACTIVITY_ID", "USERCODE"),
  CONSTRAINT "ACTIVITY_DELIVERIES_FK" FOREIGN KEY ("ACTIVITY_ID") REFERENCES ACTIVITY("ID")
);


# --- !Downs
ALTER TABLE ACTIVITY_SCOPE DROP CONSTRAINT ACTIVITY_SCOPE_FK;
ALTER TABLE ACTIVITY_RECIPIENT DROP CONSTRAINT ACTIVITY_DELIVERIES_FK;

DROP TABLE ACTIVITY_SCOPE;
DROP TABLE ACTIVITY_RECIPIENT;
DROP TABLE ACTIVITY;
