# --- !Ups
CREATE TABLE NOTIFICATION (
  "ID" nvarchar2 (100) NOT NULL,
  "PROVIDER_ID" nvarchar2 (100) NOT NULL,
  "NOTIFICATION_TYPE" nvarchar2 (100) NOT NULL,
  "TITLE" clob NOT NULL,
  "TEXT" clob NOT NULL,
  "REPLACEDBY_ID" nvarchar2 (100),
  "CREATED_AT" TIMESTAMP (6) NOT NULL,
  CONSTRAINT "NOTIFICATION_PK" PRIMARY KEY ("ID")
);

CREATE TABLE NOTIFICATION_SCOPE (
  "NOTIFICATION_ID" nvarchar2 (100) NOT NULL,
  "SCOPE_ID" nvarchar2 (255) NOT NULL,
  "SCOPE_TYPE" nvarchar2 (255) NOT NULL,
  "SCOPE_NAME" nvarchar2 (255) NOT NULL,
  CONSTRAINT "NOTIFICATION_SCOPE_PK" PRIMARY KEY ("NOTIFICATION_ID", "SCOPE_ID"),
  CONSTRAINT "NOTIFICATION_SCOPE_FK" FOREIGN KEY ("NOTIFICATION_ID") REFERENCES NOTIFICATION("ID")
);

CREATE TABLE NOTIFICATION_DELIVERIES (
  "NOTIFICATION_ID" nvarchar2 (100) NOT NULL,
  "USERCODE" nvarchar2 (10) NOT NULL,
  "SENT_AT" TIMESTAMP (6) NOT NULL,
  "SEEN_AT" TIMESTAMP (6),
  "DISMISSED_AT" TIMESTAMP (6),
  CONSTRAINT "NOTIFICATION_DELIVERIES_PK" PRIMARY KEY ("NOTIFICATION_ID", "USERCODE"),
  CONSTRAINT "NOTIFICATION_DELIVERIES_FK" FOREIGN KEY ("NOTIFICATION_ID") REFERENCES NOTIFICATION("ID")
);


# --- !Downs
DROP TABLE NOTIFICATION;
DROP TABLE NOTIFICATION_SCOPE;
DROP TABLE NOTIFICATION_DELIVERIES;