# --- !Ups
CREATE TABLE ACTIVITY (
  "ID" nvarchar2 (100) NOT NULL,
  "PROVIDER_ID" nvarchar2 (100) NOT NULL,
  "TYPE" nvarchar2 (100) NOT NULL,
  "TITLE" clob NOT NULL,
  "TEXT" clob NOT NULL,
  "REPLACED_BY_ID" nvarchar2 (100),
  "GENERATED_AT" TIMESTAMP (6) NOT NULL,
  "CREATED_AT" TIMESTAMP (6) NOT NULL,
  "SHOULD_NOTIFY" NUMBER (1, 0) DEFAULT 0 NOT NULL,
  CONSTRAINT "ACTIVITY_PK" PRIMARY KEY ("ID")
);

CREATE TABLE ACTIVITY_TAG (
  "ACTIVITY_ID" nvarchar2 (100) NOT NULL,
  "ID" nvarchar2 (100) NOT NULL,
  "NAME" nvarchar2 (255) NOT NULL,
  "VALUE" nvarchar2 (255) NOT NULL,
  "CREATED_AT" TIMESTAMP (6) NOT NULL,
  CONSTRAINT "ACTIVITY_TAG_PK" PRIMARY KEY ("ACTIVITY_ID", "ID"),
  CONSTRAINT "ACTIVITY_TAG_FK" FOREIGN KEY ("ACTIVITY_ID") REFERENCES ACTIVITY("ID")
);

CREATE TABLE ACTIVITY_RECIPIENT (
  "ACTIVITY_ID" nvarchar2 (100) NOT NULL,
  "USERCODE" nvarchar2 (10) NOT NULL,
  "CREATED_AT" TIMESTAMP (6) NOT NULL,
  "SENT_AT" TIMESTAMP (6),
  "SEEN_AT" TIMESTAMP (6),
  "DISMISSED_AT" TIMESTAMP (6),
  CONSTRAINT "ACTIVITY_RECIPIENT_PK" PRIMARY KEY ("ACTIVITY_ID", "USERCODE"),
  CONSTRAINT "ACTIVITY_RECIPIENT_FK" FOREIGN KEY ("ACTIVITY_ID") REFERENCES ACTIVITY("ID")
);

CREATE INDEX ACTIVITY_TAG_FK_INDEX ON ACTIVITY_TAG (ACTIVITY_ID);
CREATE INDEX ACTIVITY_RECIP_FK_INDEX ON ACTIVITY_RECIPIENT (ACTIVITY_ID);

# --- !Downs
DROP INDEX ACTIVITY_RECIP_FK_INDEX;
DROP INDEX ACTIVITY_TAG_FK_INDEX;

ALTER TABLE ACTIVITY_TAG DROP CONSTRAINT ACTIVITY_TAG_FK;
ALTER TABLE ACTIVITY_RECIPIENT DROP CONSTRAINT ACTIVITY_RECIPIENT_FK;

DROP TABLE ACTIVITY_TAG;
DROP TABLE ACTIVITY_RECIPIENT;
DROP TABLE ACTIVITY;
