# --- !Ups
ALTER TABLE USER_TILE RENAME COLUMN TILE_POSITION TO TILE_POSITION_MOBILE;
ALTER TABLE USER_TILE ADD TILE_POSITION_DESKTOP NUMBER;
ALTER TABLE TILE RENAME COLUMN DEFAULT_POSITION TO DEFAULT_POSITION_MOBILE;
ALTER TABLE TILE ADD DEFAULT_POSITION_DESKTOP NUMBER;

# --- !Downs
ALTER TABLE USER_TILE RENAME COLUMN TILE_POSITION_MOBILE TO TILE_POSITION;
ALTER TABLE USER_TILE DROP COLUMN TILE_POSITION_DESKTOP;
ALTER TABLE TILE RENAME COLUMN DEFAULT_POSITION_MOBILE TO DEFAULT_POSITION;
ALTER TABLE TILE DROP COLUMN DEFAULT_POSITION_DESKTOP;
