# --- !Ups
CREATE TABLE USER_TILE_LAYOUT (
  "USERCODE"     NVARCHAR2(100),
  "TILE_ID"      NVARCHAR2(100),
  "LAYOUT_WIDTH" INT          NOT NULL,
  "X"            INT          NOT NULL,
  "Y"            INT          NOT NULL,
  "WIDTH"        INT          NOT NULL,
  "HEIGHT"       INT          NOT NULL,
  CONSTRAINT "USER_TILE_LAYOUT_PREF_FK" FOREIGN KEY ("TILE_ID") REFERENCES TILE ("ID"),
  CONSTRAINT "USER_TILE_LAYOUT_PREF_PK" PRIMARY KEY ("USERCODE", "TILE_ID", "LAYOUT_WIDTH")
);

ALTER TABLE USER_TILE DROP COLUMN TILE_POSITION;
ALTER TABLE USER_TILE DROP COLUMN TILE_SIZE;

# --- !Downs
DROP TABLE USER_TILE_LAYOUT;

ALTER TABLE USER_TILE ADD "TILE_POSITION" INT DEFAULT 0 NOT NULL;
ALTER TABLE USER_TILE ADD "TILE_SIZE" NVARCHAR2(100);
