# --- !Ups
CREATE TABLE TILE_GROUP_LAYOUT (
  "GROUP_ID"        NVARCHAR2(100),
  "TILE_ID"      NVARCHAR2(100),
  "LAYOUT_WIDTH" INT NOT NULL,
  "X"            INT NOT NULL,
  "Y"            INT NOT NULL,
  "WIDTH"        INT NOT NULL,
  "HEIGHT"       INT NOT NULL,
  CONSTRAINT "TILE_GROUP_LAYOUT_PK" PRIMARY KEY ("GROUP_ID", "TILE_ID"),
  CONSTRAINT "TILE_GROUP_LAYOUT_FK" FOREIGN KEY ("GROUP_ID", "TILE_ID") REFERENCES TILE_GROUP ("GROUP", "TILE_ID")
);

# --- !Downs
DROP TABLE TILE_GROUP_LAYOUT;
