# --- !Ups
CREATE TABLE TILE_GROUP_LAYOUT (
  "GROUP_ID"        NVARCHAR2(100),
  "TILE_ID"      NVARCHAR2(100),
  "LAYOUT_WIDTH" INT NOT NULL,
  "X"            INT NOT NULL,
  "Y"            INT NOT NULL,
  "WIDTH"        INT NOT NULL,
  "HEIGHT"       INT NOT NULL,
  CONSTRAINT "TILE_GROUP_LAYOUT_PK" PRIMARY KEY ("GROUP_ID", "TILE_ID"),
  CONSTRAINT "TILE_GROUP_LAYOUT_FK" FOREIGN KEY ("GROUP_ID", "TILE_ID") REFERENCES TILE_GROUP ("GROUP", "TILE_ID")
);

ALTER TABLE TILE DROP COLUMN DEFAULT_POSITION;
ALTER TABLE TILE DROP COLUMN DEFAULT_SIZE;

# --- !Downs
DROP TABLE TILE_GROUP_LAYOUT;

ALTER TABLE TILE ADD "DEFAULT_POSITION" INT DEFAULT 0 NOT NULL;
ALTER TABLE TILE ADD "DEFAULT_SIZE" NVARCHAR2(100) DEFAULT 'small' NOT NULL;
