# --- !Ups
ALTER TABLE TILE_GROUP_LAYOUT
  DROP CONSTRAINT TILE_GROUP_LAYOUT_PK;

ALTER TABLE TILE_GROUP_LAYOUT
  ADD CONSTRAINT TILE_GROUP_LAYOUT_PK PRIMARY KEY (GROUP_ID, TILE_ID, LAYOUT_WIDTH);

# --- !Downs
ALTER TABLE TILE_GROUP_LAYOUT
  DROP CONSTRAINT TILE_GROUP_LAYOUT_PK;

ALTER TABLE TILE_GROUP_LAYOUT
  ADD CONSTRAINT TILE_GROUP_LAYOUT_PK PRIMARY KEY (GROUP_ID, TILE_ID);