# --- !Ups
CREATE TABLE NEWS_ITEM (
  ID           NVARCHAR2(100),
  TITLE        CLOB NOT NULL,
  TEXT         CLOB NOT NULL,
  CREATED_AT   TIMESTAMP (6) NOT NULL,
  PUBLISH_DATE TIMESTAMP (6) NOT NULL,
  LINK_TEXT    NVARCHAR2(4000),
  LINK_HREF    NVARCHAR2(4000),
  CONSTRAINT "NEWS_ITEM_PK" PRIMARY KEY ("ID")
);

CREATE TABLE NEWS_RECIPIENT (
  NEWS_ITEM_ID NVARCHAR2(100),
  USERCODE     NVARCHAR2(100),
  PUBLISH_DATE TIMESTAMP (6) NOT NULL
);

CREATE INDEX NEWS_ITEM_INDEX ON NEWS_ITEM (PUBLISH_DATE DESC);
CREATE INDEX NEWS_RECIP_INDEX ON NEWS_RECIPIENT (USERCODE, PUBLISH_DATE DESC);

# --- !Downs
DROP TABLE NEWS_ITEM;
DROP TABLE NEWS_RECIPIENT;
