# --- !Ups
CREATE TABLE NEWS_IMAGE (
  ID             NVARCHAR2(100),
  WIDTH          NUMBER         NOT NULL,
  HEIGHT         NUMBER         NOT NULL,
  CONTENT_LENGTH NUMBER         NOT NULL,
  CONTENT_TYPE   NVARCHAR2(100) NOT NULL,
  CREATED_AT     TIMESTAMP(0)   NOT NULL,
  CONSTRAINT "NEWS_IMAGE_PK" PRIMARY KEY ("ID")
);

ALTER TABLE NEWS_ITEM ADD NEWS_IMAGE_ID NVARCHAR2(100);
ALTER TABLE NEWS_ITEM ADD CONSTRAINT NEWS_ITEM_IMAGE_FK FOREIGN KEY (NEWS_IMAGE_ID) REFERENCES NEWS_IMAGE (ID);

# --- !Downs
ALTER TABLE NEWS_ITEM DROP CONSTRAINT NEWS_ITEM_IMAGE_FK;
ALTER TABLE NEWS_ITEM DROP COLUMN NEWS_IMAGE_ID;

DROP TABLE NEWS_IMAGE;
