# --- !Ups
CREATE TABLE AUDIENCE_COMPONENT (
  "ID" NVARCHAR2(100),
  "NAME" NVARCHAR2(100),
  "VALUE" NVARCHAR2(100),
  "DEPT_CODE" NVARCHAR2(100)
);

ALTER TABLE NEWS_ITEM ADD "AUDIENCE_ID" NVARCHAR2(100);

ALTER TABLE ACTIVITY ADD "AUDIENCE_ID" NVARCHAR2(100);

# --- !Downs

ALTER TABLE NEWS_ITEM DROP COLUMN AUDIENCE_ID;
ALTER TABLE ACTIVITY DROP COLUMN AUDIENCE_ID;

DROP TABLE AUDIENCE_COMPONENT;