# --- !Ups
CREATE TABLE AUDIENCE_COMPONENT (
  "AUDIENCE_ID" NVARCHAR2(100) NOT NULL,
  "NAME" NVARCHAR2(100) NOT NULL,
  "VALUE" NVARCHAR2(100),
  "DEPT_CODE" NVARCHAR2(100)
);

CREATE INDEX AUDIENCE_COMPONENT_ID_INDEX ON AUDIENCE_COMPONENT (AUDIENCE_ID);

ALTER TABLE NEWS_ITEM ADD "AUDIENCE_ID" NVARCHAR2(100);

ALTER TABLE ACTIVITY ADD "AUDIENCE_ID" NVARCHAR2(100);

# --- !Downs

ALTER TABLE NEWS_ITEM DROP COLUMN AUDIENCE_ID;
ALTER TABLE ACTIVITY DROP COLUMN AUDIENCE_ID;

DROP INDEX AUDIENCE_COMPONENT_ID_INDEX;

DROP TABLE AUDIENCE_COMPONENT;