# --- !Ups
CREATE TABLE APP_PERMISSION (
  "APP_ID" NVARCHAR2(100) NOT NULL,
  "USERCODE" NVARCHAR2(100) NOT NULL,
  CONSTRAINT "APP_PERMISSION_PK" PRIMARY KEY ("APP_ID", "USERCODE")
);

# --- !Downs
DROP TABLE APP_PERMISSION;
