# --- !Ups
CREATE TABLE APP_PERMISSION (
  "APP_ID" NVARCHAR2(100) NOT NULL,
  "USERCODE" NVARCHAR2(100) NOT NULL
);

CREATE INDEX APP_PERMISSION_INDEX ON APP_PERMISSION (APP_ID, USERCODE);

# --- !Downs
DROP INDEX APP_PERMISSION_INDEX;

DROP TABLE APP_PERMISSION;
