# --- !Ups
CREATE TABLE PROVIDER_PERMISSION (
  "PROVIDER_ID" NVARCHAR2(100) NOT NULL,
  "USERCODE" NVARCHAR2(100) NOT NULL,
  CONSTRAINT "PROVIDER_PERMISSION_PK" PRIMARY KEY ("PROVIDER_ID", "USERCODE")
);

# --- !Downs
DROP TABLE PROVIDER_PERMISSION;
