# --- !Ups
CREATE TABLE PROVIDER (
  "ID" NVARCHAR2(100),
  "DISPLAY_NAME" NVARCHAR2(100),
  "ICON" NVARCHAR2(20),
  "COLOUR" NVARCHAR2(10),
  CONSTRAINT "PROVIDER_PK" PRIMARY KEY ("ID")
);

INSERT INTO PROVIDER (ID, DISPLAY_NAME, ICON, COLOUR) VALUES ('eating', 'Eating at Warwick', 'cutlery', '#59b399');
INSERT INTO PROVIDER (ID, DISPLAY_NAME, ICON, COLOUR) VALUES ('hearnow', 'HearNow', 'pie-chart', '#f47920');
INSERT INTO PROVIDER (ID, DISPLAY_NAME, ICON, COLOUR) VALUES ('library', 'Library', 'book', '#f47920');
INSERT INTO PROVIDER (ID, DISPLAY_NAME, ICON, COLOUR) VALUES ('photos', 'Photos', 'camera', '#59b399');
INSERT INTO PROVIDER (ID, DISPLAY_NAME, ICON, COLOUR) VALUES ('tabula', 'Tabula', 'cog', '#239b92');
INSERT INTO PROVIDER (ID, DISPLAY_NAME, ICON, COLOUR) VALUES ('websignon', 'Web Sign-on', 'lock', '#5b3069');
INSERT INTO PROVIDER (ID, DISPLAY_NAME, ICON, COLOUR) VALUES ('coursesync', 'CourseSync', 'file-text-o', '#0993b8');

ALTER TABLE PROVIDER_PERMISSION ADD CONSTRAINT "PROVIDER_PERMISSION_FK"
FOREIGN KEY ("PROVIDER_ID") REFERENCES PROVIDER("ID");

# --- !Downs
ALTER TABLE PROVIDER_PERMISSION DROP CONSTRAINT PROVIDER_PERMISSION_FK;

DROP TABLE PROVIDER;