# --- !Ups

-- NEWSTART-366 oops
-- copied from 28
CREATE TABLE NEWS_ITEM_CATEGORY (
  NEWS_ITEM_ID        NVARCHAR2(100) NOT NULL,
  PUBLISH_CATEGORY_ID NVARCHAR2(100) NOT NULL,
  CONSTRAINT NEWS_ITEM_CAT_NEWS_ITEM_FK FOREIGN KEY (NEWS_ITEM_ID) REFERENCES NEWS_ITEM (ID),
  CONSTRAINT NEWS_ITEM_PUBLISH_CAT_FK FOREIGN KEY (PUBLISH_CATEGORY_ID) REFERENCES PUBLISH_CATEGORY (ID)
);

DROP TABLE NOTIFICATION_CATEGORY;

# --- !Downs
