# --- !Ups
CREATE TABLE ACTIVITY_TYPE (
  NAME         NVARCHAR2(100) NOT NULL PRIMARY KEY,
  DISPLAY_NAME NVARCHAR2(255) NOT NULL
);

CREATE TABLE ACTIVITY_TAG_TYPE (
  NAME                   NVARCHAR2(255) NOT NULL PRIMARY KEY,
  DISPLAY_NAME           NVARCHAR2(255) NOT NULL,
  VALUE_VALIDATION_REGEX NVARCHAR2(255)
);

CREATE TABLE ACTIVITY_TAG_VALUE (
  ID            NVARCHAR2(100) NOT NULL PRIMARY KEY,
  TAG_NAME      NVARCHAR2(255) NOT NULL,
  VALUE         NVARCHAR2(255) NOT NULL,
  DISPLAY_VALUE NVARCHAR2(255) NOT NULL
);

CREATE INDEX ACTIVITY_T_V_NAME_VALUE ON ACTIVITY_TAG_VALUE(TAG_NAME, VALUE);

ALTER TABLE ACTIVITY_TAG DROP COLUMN DISPLAY_VALUE;

# --- !Downs
DROP INDEX ACTIVITY_T_V_NAME_VALUE;

ALTER TABLE ACTIVITY_TAG ADD DISPLAY_VALUE NVARCHAR2(255);

DROP TABLE ACTIVITY_TYPE;
DROP TABLE ACTIVITY_TAG_TYPE;
DROP TABLE ACTIVITY_TAG_VALUE;

