# --- !Ups

CREATE TABLE USER_NEWS_CATEGORY (
  USERCODE NVARCHAR2(100) NOT NULL,
  NEWS_CATEGORY_ID NVARCHAR2(100) NOT NULL,
  CONSTRAINT USER_NEWS_CAT_CAT_FK FOREIGN KEY (NEWS_CATEGORY_ID) REFERENCES NEWS_CATEGORY (ID)
);

CREATE INDEX USER_NEWS_CAT_USERCODE_INDEX ON USER_NEWS_CATEGORY (USERCODE);

# --- !Downs

DROP INDEX USER_NEWS_CAT_USERCODE_INDEX;

DROP TABLE USER_NEWS_CATEGORY;