# --- !Ups
DROP TABLE PROVIDER_PERMISSION;

ALTER TABLE PROVIDER ADD PUBLISHER_ID NVARCHAR2(100) DEFAULT('315d3e23-614e-4d5a-b27f-703cdb834c9b') NOT NULL; --Default Publisher
ALTER TABLE PROVIDER ADD FOREIGN KEY ("PUBLISHER_ID") REFERENCES PUBLISHER("ID");

INSERT INTO PUBLISHER (ID, NAME) VALUES ('49b3430d-aeb3-45ee-85f2-e67dd96d90c1', 'ITS Web Publishing');
UPDATE PROVIDER SET PUBLISHER_ID = '49b3430d-aeb3-45ee-85f2-e67dd96d90c1'
  WHERE ID IN ('eating', 'hearnow', 'library', 'photos', 'tabula','websignon', 'coursesync', 'printing');

# --- !Downs
CREATE TABLE PROVIDER_PERMISSION (
  "PROVIDER_ID" NVARCHAR2(100) NOT NULL,
  "USERCODE" NVARCHAR2(100) NOT NULL,
  CONSTRAINT "PROVIDER_PERMISSION_PK" PRIMARY KEY ("PROVIDER_ID", "USERCODE"),
  CONSTRAINT "PROVIDER_PERMISSION_FK" FOREIGN KEY ("PROVIDER_ID") REFERENCES PROVIDER("ID")
);
