# --- !Ups

ALTER TABLE PUBLISHED_NOTIFICATION ADD UPDATED_AT TIMESTAMP(6);
ALTER TABLE PUBLISHED_NOTIFICATION ADD UPDATED_BY NVARCHAR2(100);

# --- !Downs

ALTER TABLE PUBLISHED_NOTIFICATION DROP COLUMN UPDATED_AT;
ALTER TABLE PUBLISHED_NOTIFICATION DROP COLUMN UPDATED_BY;
