# --- !Ups

ALTER TABLE ACTIVITY ADD PUBLISHED_AT TIMESTAMP(6);
ALTER TABLE NEWS_ITEM ADD PUBLISHED_AT TIMESTAMP(6);

# --- !Downs

ALTER TABLE NEWS_ITEM DROP COLUMN PUBLISHED_AT;
ALTER TABLE ACTIVITY DROP COLUMN PUBLISHED_AT;
