# --- !Ups

ALTER TABLE PUBLISHED_NOTIFICATION ADD PUBLISHED_AT TIMESTAMP(6);
UPDATE PUBLISHED_NOTIFICATION SET PUBLISHED_AT = CREATED_AT;
ALTER TABLE PUBLISHED_NOTIFICATION MODIFY PUBLISHED_AT NOT NULL;

# --- !Downs

ALTER TABLE PUBLISHED_NOTIFICATION DROP COLUMN PUBLISHED_AT;
