# --- !Ups

ALTER TABLE ACTIVITY ADD PUBLISHER_ID NVARCHAR2(100) DEFAULT 'default' NOT NULL;
ALTER TABLE ACTIVITY ADD CREATED_BY NVARCHAR2(100) DEFAULT 'unknown' NOT NULL;

UPDATE ACTIVITY
SET PUBLISHER_ID = COALESCE((SELECT PUBLISHER_ID
                             FROM PUBLISHED_NOTIFICATION
                             WHERE ACTIVITY_ID = ACTIVITY.ID), n'default');

UPDATE ACTIVITY
SET CREATED_BY = COALESCE((SELECT CREATED_BY
                           FROM PUBLISHED_NOTIFICATION
                           WHERE ACTIVITY_ID = ACTIVITY.ID), n'unknown');

ALTER TABLE ACTIVITY ADD CONSTRAINT ACTIVITY_PUBLISHER_FK FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (ID);
CREATE INDEX ACTIVITY_PUBLISHER_INDEX ON ACTIVITY (PUBLISHER_ID);

DROP TABLE PUBLISHED_NOTIFICATION;

# --- !Downs

CREATE TABLE PUBLISHED_NOTIFICATION (
  ACTIVITY_ID NVARCHAR2(100) NOT NULL,
  PUBLISHER_ID NVARCHAR2(100) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY NVARCHAR2(100) NOT NULL,
  UPDATED_AT TIMESTAMP,
  UPDATED_BY NVARCHAR2(100),
  CONSTRAINT PUB_NOTIF_ACTIVITY_FK FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITY (ID),
  CONSTRAINT PUB_NOTIF_PUBLISHER_FK FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (ID)
);

CREATE INDEX PUB_NOTIF_PUB_IDX ON PUBLISHED_NOTIFICATION (PUBLISHER_ID);

INSERT INTO PUBLISHED_NOTIFICATION (ACTIVITY_ID, PUBLISHER_ID, CREATED_AT, CREATED_BY)
  SELECT ID, PUBLISHER_ID, CREATED_AT, CREATED_BY FROM ACTIVITY
  WHERE CREATED_BY != 'unknown';

ALTER TABLE ACTIVITY DROP COLUMN PUBLISHER_ID;
ALTER TABLE ACTIVITY DROP COLUMN CREATED_BY;

