# --- !Ups

ALTER TABLE ACTIVITY RENAME COLUMN GENERATED_AT TO PUBLISHED_AT;

DROP INDEX ACTIVITY_USERCODE_DATE_INDEX;
ALTER TABLE ACTIVITY_RECIPIENT RENAME COLUMN GENERATED_AT TO PUBLISHED_AT;
CREATE INDEX ACTIVITY_USERCODE_DATE_INDEX ON ACTIVITY_RECIPIENT (USERCODE ASC, PUBLISHED_AT DESC);

# --- !Downs

DROP INDEX ACTIVITY_USERCODE_DATE_INDEX;
ALTER TABLE ACTIVITY_RECIPIENT RENAME COLUMN PUBLISHED_AT TO GENERATED_AT;
CREATE INDEX ACTIVITY_USERCODE_DATE_INDEX ON ACTIVITY_RECIPIENT (USERCODE ASC, GENERATED_AT DESC);

ALTER TABLE ACTIVITY RENAME COLUMN PUBLISHED_AT TO GENERATED_AT;
