# --- !Ups
ALTER TABLE ACTIVITY_RECIPIENT ADD GENERATED_AT TIMESTAMP(6) NULL;
UPDATE ACTIVITY_RECIPIENT SET GENERATED_AT = CREATED_AT;
ALTER TABLE ACTIVITY_RECIPIENT MODIFY GENERATED_AT TIMESTAMP(6) NOT NULL;

CREATE INDEX ACTIVITY_USERCODE_DATE_INDEX ON ACTIVITY_RECIPIENT (USERCODE ASC, GENERATED_AT DESC);

# --- !Downs
DROP INDEX ACTIVITY_USERCODE_DATE_INDEX;

ALTER TABLE ACTIVITY_RECIPIENT DROP COLUMN GENERATED_AT;