# --- !Ups
ALTER TABLE USER_NEWS_CATEGORY ADD SELECTED NUMBER(1) NULL;
UPDATE USER_NEWS_CATEGORY SET SELECTED = 1;
INSERT INTO USER_NEWS_CATEGORY
  SELECT DISTINCT CARTESIAN.*, 0 AS SELECTED FROM USER_NEWS_CATEGORY EXISTING
    RIGHT JOIN
    (SELECT USERCODE, NEWS_CATEGORY.ID AS NEWS_CATEGORY_ID FROM USER_NEWS_CATEGORY, NEWS_CATEGORY)
    CARTESIAN ON EXISTING.USERCODE = CARTESIAN.USERCODE
                 AND EXISTING.NEWS_CATEGORY_ID = CARTESIAN.NEWS_CATEGORY_ID
  WHERE EXISTING.USERCODE IS NULL;
ALTER TABLE USER_NEWS_CATEGORY MODIFY SELECTED NUMBER(1) DEFAULT 0 NOT NULL;

# --- !Downs
ALTER TABLE USER_NEWS_CATEGORY DROP COLUMN SELECTED;
