# --- !Ups
ALTER TABLE PUSH_REGISTRATION ADD UPDATED_AT TIMESTAMP;
ALTER TABLE PUSH_REGISTRATION ADD DEVICE_STRING NVARCHAR2(200) DEFAULT null;

# --- !Downs
ALTER TABLE PUSH_REGISTRATION DROP COLUMN UPDATED_AT;
ALTER TABLE PUSH_REGISTRATION DROP COLUMN DEVICE_STRING;