# --- !Ups

CREATE INDEX ACTIVITY_RECIPIENT_READ_INDEX ON ACTIVITY_RECIPIENT (
  USERCODE,
  SHOULD_NOTIFY,
  PUBLISHED_AT DESC,
  ACTIVITY_ID ASC,
  REPLACED
) ONLINE;

DROP INDEX ACTIVITY_USERCODE_DATE_INDEX;

# --- !Downs

DELETE INDEX ACTIVITY_RECIPIENT_READ_INDEX;

CREATE INDEX ACTIVITY_USERCODE_DATE_INDEX ON ACTIVITY_RECIPIENT (USERCODE ASC, PUBLISHED_AT DESC);