# --- !Ups

CREATE TABLE USER_NEWS_OPT_IN (
  "USERCODE" NVARCHAR2(100) NOT NULL,
  "NAME"     NVARCHAR2(100) NOT NULL,
  "VALUE"    NVARCHAR2(100) NOT NULL
);
CREATE INDEX USER_NEWS_OPT_IN_USERCODE ON USER_NEWS_OPT_IN(USERCODE);
CREATE UNIQUE INDEX USER_NEWS_OPT_IN_UNIQ ON USER_NEWS_OPT_IN(USERCODE, NAME, VALUE);

# --- !Downs

DROP TABLE USER_NEWS_OPT_IN;