# --- !Ups

ALTER TABLE USER_PREFERENCE ADD NOTIFICATION_FILTER CLOB;
ALTER TABLE USER_PREFERENCE ADD ACTIVITY_FILTER CLOB;

# --- !Downs

ALTER TABLE USER_PREFERENCE DROP COLUMN NOTIFICATION_FILTER;
ALTER TABLE USER_PREFERENCE DROP COLUMN ACTIVITY_FILTER;