# --- !Ups
CREATE TABLE TILE (
  "ID"           NVARCHAR2(100),
  "TYPE"         NVARCHAR2(100) NOT NULL,
  "DEFAULT_SIZE" NVARCHAR2(100) NOT NULL,
  CONSTRAINT "TILE_PK" PRIMARY KEY ("ID")
);

CREATE TABLE USER_TILE_PREF (
"USERCODE"     NVARCHAR2(100),
"TILE_ID"      NVARCHAR2(100),
"TILE_XPOS"    INT          NOT NULL,
"TILE_YPOS"    INT          NOT NULL,
"SIZE"         NVARCHAR2(100),
"CREATED_AT"   TIMESTAMP(6) NOT NULL,
"LAST_CHANGED" TIMESTAMP(6) NOT NULL,
CONSTRAINT "USER_TILE_PREF_FK" FOREIGN KEY ("TILE_ID") REFERENCES TILE ("ID"),
CONSTRAINT "USER_TILE_PREF_PK" PRIMARY KEY ("USERCODE", "TILE_ID")
);

INSERT INTO TILE VALUES ('mail', 'list', 'large');
INSERT INTO TILE VALUES ('tabula', 'bignumber', 'small');
INSERT INTO TILE VALUES ('live-departures', 'list', 'small');
INSERT INTO TILE VALUES ('modules', 'bignumber', 'small');

# --- !Downs
DROP TABLE USER_TILE_PREF;
DROP TABLE TILE;
