# --- !Ups

CREATE TABLE USER_EMAIL_NOTIFICATIONS_PREF (
  "USERCODE"    NVARCHAR2(100) NOT NULL,
  "WANTS_EMAIL" NUMBER(1,0) DEFAULT 1 NOT NULL
);

CREATE INDEX USER_EMAIL_NOTIFICATIONS_PREF_USERCODE ON USER_EMAIL_NOTIFICATIONS_PREF(USERCODE);
CREATE UNIQUE INDEX USER_EMAIL_NOTIFICATIONS_PREF_USERCODE_UNIQUE ON USER_EMAIL_NOTIFICATIONS_PREF(USERCODE);

# --- !Downs

DROP TABLE USER_EMAIL_NOTIFICATIONS_PREF;
