# --- !Ups

ALTER TABLE PROVIDER ADD SEND_EMAIL NUMBER(1, 0) DEFAULT 0 NOT NULL;
ALTER TABLE ACTIVITY ADD SEND_EMAIL NUMBER(1, 0) NULL;

# --- !Downs

ALTER TABLE PROVIDER DROP COLUMN SEND_EMAIL;
ALTER TABLE ACTIVITY DROP COLUMN SEND_EMAIL;