# --- !Ups

ALTER TABLE USER_PREFERENCE ADD WANTS_SMS NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE USER_PREFERENCE ADD SMS_NUMBER NVARCHAR2(100) NULL;

# --- !Downs

ALTER TABLE USER_PREFERENCE DROP COLUMN WANTS_SMS;
ALTER TABLE USER_PREFERENCE DROP COLUMN SMS_NUMBER;
