# --- !Ups
CREATE TABLE TILE_GROUP (
  "TILE_ID"     NVARCHAR2(100) NOT NULL,
  "GROUP"       NVARCHAR2(100) NOT NULL,
  CONSTRAINT  "TILE_GROUPS_FK" FOREIGN KEY ("TILE_ID") REFERENCES TILE (ID),
  CONSTRAINT  "TILE_GROUPS_PK" PRIMARY KEY ("GROUP", TILE_ID)
);
ALTER TABLE TILE ADD "DEFAULT_POSITION" INT DEFAULT 0 NOT NULL;
ALTER TABLE USER_TILE ADD REMOVED NUMBER (1, 0) DEFAULT 0 NOT NULL;

# --- !Downs

DROP TABLE TILE_GROUP;
ALTER TABLE TILE DROP COLUMN DEFAULT_POSITION;
ALTER TABLE USER_TILE DROP COLUMN REMOVED;
