# --- !Ups
alter table USER_PREFERENCE add SMS_VERIFICATION NVARCHAR2(6) null;
ALTER TABLE USER_PREFERENCE ADD SMS_NUMBER_TO_VERIFY NVARCHAR2(100) NULL;

# --- !Downs
alter table USER_PREFERENCE drop column SMS_VERIFICATION;
alter table USER_PREFERENCE drop column SMS_NUMBER_TO_VERIFY;

