# --- !Ups
INSERT INTO TILE_GROUP (TILE_ID, "GROUP") SELECT TILE_ID, 'other' FROM TILE_GROUP WHERE "GROUP" = 'staff';
INSERT INTO TILE_GROUP_LAYOUT (GROUP_ID, TILE_ID, LAYOUT_WIDTH, X, Y, WIDTH, HEIGHT) SELECT 'other', TILE_ID, LAYOUT_WIDTH, X, Y, WIDTH, HEIGHT FROM TILE_GROUP_LAYOUT WHERE GROUP_ID = 'staff';

# --- !Downs
DELETE FROM TILE_GROUP_LAYOUT WHERE GROUP_ID = 'other';
DELETE FROM TILE_GROUP WHERE "GROUP" = 'other';
