# --- !Ups
CREATE TABLE TIMETABLE_TOKEN (
  TOKEN        NVARCHAR2(100),
  USERCODE     NVARCHAR2(100) NOT NULL,
  LAST_USED_AT TIMESTAMP,
  CONSTRAINT "TIMETABLE_TOKEN_PK" PRIMARY KEY ("TOKEN")
);

# --- !Downs
DROP TABLE TIMETABLE_TOKEN;

