# --- !Ups
CREATE TABLE TIMETABLE_TOKEN (
  ID           NVARCHAR2(100) PRIMARY KEY,
  USERCODE     NVARCHAR2(100) NOT NULL,
  TOKEN        NVARCHAR2(100) NOT NULL UNIQUE,
  LAST_USED_AT TIMESTAMP
);

# --- !Downs
DROP TABLE TIMETABLE_TOKEN;

