# --- !Ups
CREATE TABLE DO_NOT_DISTURB(
  USERCODE NVARCHAR2(100) NOT NULL,
  START_HR NUMBER(2),
  START_MIN NUMBER(2),
  END_HR NUMBER(2),
  END_MIN NUMBER(2),
  CONSTRAINT DO_NOT_DISTURB_USERCODE_FK FOREIGN KEY (USERCODE) REFERENCES USER_PREFERENCE(USERCODE),
  CONSTRAINT DO_NOT_DISTURB_PK PRIMARY KEY (USERCODE)
)

# --- !Downs
DROP TABLE DO_NOT_DISTURB;

