# --- !Ups
ALTER TABLE USER_TILE ALTER COLUMN TILE_POSITION RENAME TO TILE_POSITION_MOBILE;
ALTER TABLE USER_TILE ADD TILE_POSITION_DESKTOP NUMBER DEFAULT 0 NOT NULL;
ALTER TABLE TILE ALTER COLUMN DEFAULT_POSITION RENAME TO DEFAULT_POSITION_MOBILE;
ALTER TABLE TILE ADD DEFAULT_POSITION_DESKTOP NUMBER DEFAULT 0 NOT NULL;

# --- !Downs
ALTER TABLE USER_TILE ALTER COLUMN TILE_POSITION_MOBILE RENAME TO TILE_POSITION;
ALTER TABLE USER_TILE DROP COLUMN TILE_POSITION_DESKTOP;
ALTER TABLE TILE ALTER COLUMN DEFAULT_POSITION_MOBILE RENAME TO DEFAULT_POSITION;
ALTER TABLE TILE DROP COLUMN DEFAULT_POSITION_DESKTOP;
