# --- !Ups
ALTER TABLE TILE_GROUP_LAYOUT
  DROP CONSTRAINT TILE_GROUP_LAYOUT_FK;

ALTER TABLE TILE_GROUP_LAYOUT
  DROP PRIMARY KEY;

ALTER TABLE TILE_GROUP_LAYOUT
  ADD CONSTRAINT TILE_GROUP_LAYOUT_PK PRIMARY KEY (GROUP_ID, TILE_ID, LAYOUT_WIDTH);

ALTER TABLE TILE_GROUP_LAYOUT
  ADD CONSTRAINT TILE_GROUP_LAYOUT_FK FOREIGN KEY ("GROUP_ID", "TILE_ID") REFERENCES TILE_GROUP ("GROUP", "TILE_ID")

# --- !Downs
ALTER TABLE TILE_GROUP_LAYOUT
  DROP CONSTRAINT TILE_GROUP_LAYOUT_FK;

ALTER TABLE TILE_GROUP_LAYOUT
  DROP PRIMARY KEY;

ALTER TABLE TILE_GROUP_LAYOUT
  ADD CONSTRAINT TILE_GROUP_LAYOUT_PK PRIMARY KEY (GROUP_ID, TILE_ID);

ALTER TABLE TILE_GROUP_LAYOUT
  ADD CONSTRAINT TILE_GROUP_LAYOUT_FK FOREIGN KEY ("GROUP_ID", "TILE_ID") REFERENCES TILE_GROUP ("GROUP", "TILE_ID")