# --- !Ups

ALTER TABLE PUBLISH_CATEGORY RENAME TO NEWS_CATEGORY;
ALTER TABLE NEWS_ITEM_CATEGORY ALTER COLUMN PUBLISH_CATEGORY_ID RENAME TO NEWS_CATEGORY_ID;

# --- !Downs

ALTER TABLE NEWS_ITEM_CATEGORY ALTER COLUMN NEWS_CATEGORY_ID RENAME TO PUBLISH_CATEGORY_ID;
ALTER TABLE NEWS_CATEGORY RENAME TO PUBLISH_CATEGORY;
