# --- !Ups

ALTER TABLE ACTIVITY ALTER COLUMN GENERATED_AT RENAME TO PUBLISHED_AT;
ALTER TABLE ACTIVITY_RECIPIENT ALTER COLUMN GENERATED_AT RENAME TO PUBLISHED_AT;

# --- !Downs

ALTER TABLE ACTIVITY ALTER COLUMN PUBLISHED_AT RENAME TO GENERATED_AT;
ALTER TABLE ACTIVITY_RECIPIENT ALTER COLUMN PUBLISHED_AT RENAME TO GENERATED_AT;
