#!/bin/bash

DIRNAME=`dirname $0`
cd $DIRNAME/..

if [[ ! -f node_modules/.bin/gulp ]]; then
  "No gulp script found, have you run `npm install`?"
  exit 1
fi

# We set JS_MANGLE=false so that variables have their original name.
JS_MANGLE=false ./node_modules/.bin/gulp watch-assets
